export type TemplateId =
  // Section 0: Luxury & High-End Studio (10 templates)
  | "minimal-luxury"
  | "midnight-gold"
  | "clean-modern"
  | "neon-cyber"
  | "royal-emerald"
  | "pastel-bloom"
  | "sunset-glow"
  | "nordic-slate"
  | "festive-crimson"
  | "editorial-vogue"
  // Section 1: Navratri Utsav (8 templates)
  | "navratri-garba-utsav"
  | "navratri-durga-shakti"
  | "navratri-mirror-kutch"
  | "navratri-dandiya-beats"
  | "navratri-chaniya-festive"
  | "navratri-navdurga-blessings"
  | "navratri-raas-leela"
  | "navratri-golden-thali"
  // Section 2: Dussehra & Vijayadashami (8 templates)
  | "dussehra-golden-bow"
  | "dussehra-victory-flame"
  | "dussehra-royal-marigold"
  | "dussehra-shubh-apta"
  | "dussehra-ravan-dahan"
  | "dussehra-shastra-puja"
  | "dussehra-ayudha-utsav"
  | "dussehra-vijaya-parv"
  // Section 3: Shubh Deepavali (9 templates)
  | "diwali-sacred-diya"
  | "diwali-rangoli-mandala"
  | "diwali-akash-kandil"
  | "diwali-royal-sparklers"
  | "diwali-dhamaka-gold"
  | "diwali-dhanteras-shubh"
  | "diwali-laxmi-puja"
  | "diwali-bhai-dooj"
  | "diwali-patakha-celebration";

export interface CardTemplateInfo {
  id: TemplateId;
  name: string;
  category: string;
  description: string;
  tag: string;
  isDark: boolean;
  accentHex: string;
  accentBgClass: string;
  containerBg: string;
  cardGradClass: string;
  borderClass: string;
  titleColorClass: string;
  priceColorClass: string;
  ctaClass: string;
  tagBadgeClass: string;
  festivalSection?: "navratri" | "dussehra" | "diwali" | "luxury";
  headline?: string;
  tagline?: string;
}

export const CARD_TEMPLATES_INFO: CardTemplateInfo[] = [
  // ================= 10 LUXURY & HIGH-END STUDIO =================
  {
    id: "minimal-luxury",
    name: "Luxury Minimalist",
    category: "High-End & Designer",
    festivalSection: "luxury",
    description: "Ivory tones, obsidian serif styling, and champagne gold accents",
    tag: "LUXE",
    isDark: false,
    accentHex: "#D4AF37",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-white",
    cardGradClass: "from-stone-50 via-amber-50/30 to-stone-100",
    borderClass: "border-stone-300 dark:border-stone-700",
    titleColorClass: "text-stone-900 font-serif",
    priceColorClass: "text-amber-700",
    ctaClass: "bg-stone-900 text-stone-50",
    tagBadgeClass: "bg-amber-100 text-amber-800 border-amber-300",
    headline: "Exquisite Signature Edition",
    tagline: "Unmatched Craftsmanship & Timeless Luxury",
  },
  {
    id: "midnight-gold",
    name: "Midnight Prestige",
    category: "Prestige & Premium",
    festivalSection: "luxury",
    description: "Deep obsidian gradient with metallic 24K gold foil badges",
    tag: "PRESTIGE",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-400",
    containerBg: "bg-slate-900",
    cardGradClass: "from-slate-950 via-indigo-950/80 to-slate-900",
    borderClass: "border-amber-500/40",
    titleColorClass: "text-white font-sans",
    priceColorClass: "text-amber-400",
    ctaClass: "bg-amber-500 text-slate-950 font-bold",
    tagBadgeClass: "bg-indigo-950/90 text-amber-300 border-amber-500/50",
    headline: "The Royal Midnight Collection",
    tagline: "Curated Excellence for the Discerning Buyer",
  },
  {
    id: "clean-modern",
    name: "Studio Clean White",
    category: "Tech & Lifestyle",
    festivalSection: "luxury",
    description: "Crisp white studio layout with electric indigo focus",
    tag: "MODERN",
    isDark: false,
    accentHex: "#4F46E5",
    accentBgClass: "bg-indigo-600",
    containerBg: "bg-white",
    cardGradClass: "from-slate-50 via-indigo-50/40 to-slate-100",
    borderClass: "border-slate-300 dark:border-slate-700",
    titleColorClass: "text-slate-900 font-sans",
    priceColorClass: "text-indigo-600",
    ctaClass: "bg-indigo-600 text-white",
    tagBadgeClass: "bg-indigo-100 text-indigo-700 border-indigo-200",
    headline: "Studio Showcase Special",
    tagline: "Minimalist Perfection Meets Pure Performance",
  },
  {
    id: "neon-cyber",
    name: "Cyber Neon Drop",
    category: "Gaming & Streetwear",
    festivalSection: "luxury",
    description: "Dark carbon canvas with radiant cyan and violet glow",
    tag: "LIMITED DROP",
    isDark: true,
    accentHex: "#06B6D4",
    accentBgClass: "bg-cyan-500",
    containerBg: "bg-zinc-950",
    cardGradClass: "from-black via-zinc-950 to-neutral-900",
    borderClass: "border-cyan-500/40",
    titleColorClass: "text-white font-sans",
    priceColorClass: "text-cyan-400",
    ctaClass: "bg-gradient-to-r from-cyan-500 to-fuchsia-500 text-black font-bold",
    tagBadgeClass: "bg-black text-cyan-400 border-cyan-400/60",
    headline: "Limited Drop • Exclusive Release",
    tagline: "Next-Gen Futuristic Design & Premium Build",
  },
  {
    id: "royal-emerald",
    name: "Imperial Emerald",
    category: "Jewellery & Ethnic",
    festivalSection: "luxury",
    description: "Regal forest green with warm polished brass borders",
    tag: "HERITAGE",
    isDark: true,
    accentHex: "#10B981",
    accentBgClass: "bg-emerald-500",
    containerBg: "bg-emerald-950",
    cardGradClass: "from-emerald-950 via-teal-950 to-emerald-900",
    borderClass: "border-amber-400/40",
    titleColorClass: "text-emerald-50 font-serif",
    priceColorClass: "text-amber-300",
    ctaClass: "bg-amber-500 text-emerald-950 font-bold",
    tagBadgeClass: "bg-emerald-900 text-amber-300 border-amber-400/50",
    headline: "Imperial Royal Heritage",
    tagline: "Timeless Elegance Infused with Regal Grandeur",
  },
  {
    id: "pastel-bloom",
    name: "Soft Pastel Chic",
    category: "Beauty & Fashion",
    festivalSection: "luxury",
    description: "Delicate blush and rose gold tones with soft organic curves",
    tag: "TRENDING",
    isDark: false,
    accentHex: "#F43F5E",
    accentBgClass: "bg-rose-500",
    containerBg: "bg-white",
    cardGradClass: "from-rose-50 via-pink-50 to-rose-100",
    borderClass: "border-rose-200",
    titleColorClass: "text-rose-950 font-sans",
    priceColorClass: "text-rose-600",
    ctaClass: "bg-rose-500 text-white",
    tagBadgeClass: "bg-rose-100 text-rose-700 border-rose-200",
    headline: "Trending Chic Collection",
    tagline: "Effortless Grace for Every Occasion",
  },
  {
    id: "sunset-glow",
    name: "Sunset Radiance",
    category: "Summer & Activewear",
    festivalSection: "luxury",
    description: "Blazing amber to magenta sunset energy with high-contrast text",
    tag: "HOT DEAL",
    isDark: true,
    accentHex: "#F97316",
    accentBgClass: "bg-orange-500",
    containerBg: "bg-amber-950",
    cardGradClass: "from-purple-950 via-orange-950 to-amber-950",
    borderClass: "border-orange-500/40",
    titleColorClass: "text-white font-sans",
    priceColorClass: "text-orange-400",
    ctaClass: "bg-orange-500 text-white font-bold",
    tagBadgeClass: "bg-orange-950 text-orange-300 border-orange-500/50",
    headline: "Golden Hour Special Offer",
    tagline: "Vibrant Energy & Unstoppable Comfort",
  },
  {
    id: "nordic-slate",
    name: "Nordic Minimalist",
    category: "Industrial & Minimal",
    festivalSection: "luxury",
    description: "Muted charcoal and brushed steel with Swiss typographic precision",
    tag: "STUDIO",
    isDark: true,
    accentHex: "#38BDF8",
    accentBgClass: "bg-sky-500",
    containerBg: "bg-slate-900",
    cardGradClass: "from-slate-900 to-zinc-900",
    borderClass: "border-slate-700",
    titleColorClass: "text-slate-100 font-sans",
    priceColorClass: "text-sky-400",
    ctaClass: "bg-sky-500 text-slate-950 font-bold",
    tagBadgeClass: "bg-slate-800 text-sky-300 border-slate-700",
    headline: "Precision Engineered Series",
    tagline: "Form Follows Perfection with Pure Functionality",
  },
  {
    id: "festive-crimson",
    name: "Festive Crimson",
    category: "Festive & Wedding",
    festivalSection: "luxury",
    description: "Regal ruby crimson with celebratory marigold yellow flourishes",
    tag: "CELEBRATION",
    isDark: true,
    accentHex: "#EF4444",
    accentBgClass: "bg-red-500",
    containerBg: "bg-red-950",
    cardGradClass: "from-red-950 via-rose-950 to-red-900",
    borderClass: "border-yellow-400/40",
    titleColorClass: "text-rose-100 font-serif",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-yellow-400 text-red-950 font-bold",
    tagBadgeClass: "bg-red-900 text-yellow-300 border-yellow-400/50",
    headline: "Grand Festive Celebration",
    tagline: "Celebrate Moments of Joy with Pure Elegance",
  },
  {
    id: "editorial-vogue",
    name: "Editorial Vogue",
    category: "Couture & Editorial",
    festivalSection: "luxury",
    description: "High-contrast monochrome couture layout with vivid scarlet accents",
    tag: "LIMITED EDIT",
    isDark: false,
    accentHex: "#DC2626",
    accentBgClass: "bg-red-600",
    containerBg: "bg-stone-100",
    cardGradClass: "from-white via-stone-50 to-stone-200",
    borderClass: "border-stone-900",
    titleColorClass: "text-stone-950 font-serif",
    priceColorClass: "text-red-600",
    ctaClass: "bg-stone-950 text-white font-bold",
    tagBadgeClass: "bg-stone-900 text-stone-100 border-stone-800",
    headline: "The Haute Couture Issue",
    tagline: "Redefining Contemporary Style Statements",
  },

  // ================= 8 NAVRATRI UTSAV CARDS =================
  {
    id: "navratri-garba-utsav",
    name: "Garba Night Utsav",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Royal Gujarati palace archway with crossed Dandiya sticks, marigold toran & glowing lanterns",
    tag: "NAVRATRI SPECIAL",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-[#180828]",
    cardGradClass: "from-[#2A0845] via-[#4A0E4E] to-[#120320]",
    borderClass: "border-amber-400/60",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-purple-900 text-amber-300 border-amber-400",
    headline: "Navratri Garba Special Offer!",
    tagline: "Dance to the Festive Beats with This Premium Pick!",
  },
  {
    id: "navratri-durga-shakti",
    name: "Maa Durga Shakti",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Sacred golden Trishul with radiating divine sun halo, marigold garlands & royal crimson silk backdrop",
    tag: "DURGA UTSAV",
    isDark: true,
    accentHex: "#DC2626",
    accentBgClass: "bg-red-600",
    containerBg: "bg-[#280509]",
    cardGradClass: "from-[#4A050D] via-[#6B0813] to-[#1F0205]",
    borderClass: "border-amber-400/70",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-500 text-red-950 font-black",
    tagBadgeClass: "bg-red-900 text-yellow-300 border-yellow-400",
    headline: "Maa Durga Festive Blessings!",
    tagline: "Invoke Divine Elegance & Power in Every Walk!",
  },
  {
    id: "navratri-mirror-kutch",
    name: "Kutch Mirror Heritage",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Authentic Gujarati Bandhani & diamond-cut mirrorwork border with sparkling festive starlight",
    tag: "KUTCH CRAFT",
    isDark: true,
    accentHex: "#06B6D4",
    accentBgClass: "bg-cyan-500",
    containerBg: "bg-[#071322]",
    cardGradClass: "from-[#081F38] via-[#0E355E] to-[#040C16]",
    borderClass: "border-cyan-400/60",
    titleColorClass: "text-cyan-100 font-serif font-black",
    priceColorClass: "text-amber-300",
    ctaClass: "bg-gradient-to-r from-cyan-400 to-teal-300 text-slate-950 font-black",
    tagBadgeClass: "bg-cyan-950 text-cyan-300 border-cyan-400",
    headline: "Navratri Heritage Special!",
    tagline: "Shine Bright with Handcrafted Traditional Splendor!",
  },
  {
    id: "navratri-dandiya-beats",
    name: "Dandiya Beats Special",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Dandiya raas rhythm wave with ghungroo bells, marigold drops & royal purple backdrop",
    tag: "DANDIYA SPECIAL",
    isDark: true,
    accentHex: "#10B981",
    accentBgClass: "bg-emerald-500",
    containerBg: "bg-[#0B1E17]",
    cardGradClass: "from-[#0D2E23] via-[#144737] to-[#061510]",
    borderClass: "border-emerald-400/60",
    titleColorClass: "text-emerald-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-emerald-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-emerald-950 text-emerald-300 border-emerald-400",
    headline: "Dandiya Beats Festive Mega Deal!",
    tagline: "Celebrate the 9 Nights of Rhythm & Grandeur!",
  },
  {
    id: "navratri-chaniya-festive",
    name: "Chaniya Choli Festive",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Regal Gujarati latkan tassels, hanging saffron pompoms & embroidered floral arch",
    tag: "FESTIVE ETHNIC",
    isDark: true,
    accentHex: "#F97316",
    accentBgClass: "bg-orange-500",
    containerBg: "bg-[#250E04]",
    cardGradClass: "from-[#3D1807] via-[#5C240B] to-[#1A0A03]",
    borderClass: "border-orange-400/60",
    titleColorClass: "text-orange-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-orange-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-orange-950 text-orange-300 border-orange-400",
    headline: "Traditional Navratri Festive Offer!",
    tagline: "Add Vibrant Festive Joy to Your Celebrations!",
  },
  {
    id: "navratri-navdurga-blessings",
    name: "Navdurga Divine Grace",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "9 Sacred Diyas arch with golden floral kalash, temple bells & marigold garlands",
    tag: "NAVDURGA 9",
    isDark: true,
    accentHex: "#FACC15",
    accentBgClass: "bg-yellow-400",
    containerBg: "bg-[#1E0824]",
    cardGradClass: "from-[#350F3F] via-[#541864] to-[#15051A]",
    borderClass: "border-yellow-400/70",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-400 text-black font-black",
    tagBadgeClass: "bg-purple-950 text-yellow-300 border-yellow-400",
    headline: "Navdurga 9-Day Sacred Sale!",
    tagline: "Blessed with Grace, Crafted for Perfection!",
  },
  {
    id: "navratri-raas-leela",
    name: "Royal Raas Leela",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Full moon moonlight glow with golden palace pillars, hanging mogra swags & lotus blossoms",
    tag: "ROYAL RAAS",
    isDark: true,
    accentHex: "#EC4899",
    accentBgClass: "bg-pink-500",
    containerBg: "bg-[#1F081E]",
    cardGradClass: "from-[#3A0F38] via-[#5E185B] to-[#140513]",
    borderClass: "border-pink-400/60",
    titleColorClass: "text-pink-100 font-serif font-black",
    priceColorClass: "text-amber-300",
    ctaClass: "bg-gradient-to-r from-pink-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-pink-950 text-pink-300 border-pink-400",
    headline: "Royal Raas Leela Festival Deal!",
    tagline: "Step into the Moonlight with Unrivaled Glamour!",
  },
  {
    id: "navratri-golden-thali",
    name: "Aarti Thali Splendor",
    category: "Navratri Special",
    festivalSection: "navratri",
    description: "Sacred golden puja thali motif with burning camphor flames, kumkum swatches & marigold petals",
    tag: "AARTI SPLENDOR",
    isDark: true,
    accentHex: "#EAB308",
    accentBgClass: "bg-yellow-500",
    containerBg: "bg-[#2A0505]",
    cardGradClass: "from-[#470909] via-[#6E0E0E] to-[#1C0303]",
    borderClass: "border-yellow-400/80",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-orange-400 text-red-950 font-black",
    tagBadgeClass: "bg-red-950 text-yellow-300 border-yellow-400",
    headline: "Shubh Navratri Maha Offer!",
    tagline: "Pure Sacred Craftsmanship for Auspicious Festivities!",
  },

  // ================= 8 DUSSEHRA & VIJAYADASHAMI CARDS =================
  {
    id: "dussehra-golden-bow",
    name: "Vijay Dhanush Kodanda",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Shri Ram Kodanda golden bow & arrow drawing light across royal crimson skies with palace arch",
    tag: "VIJAY DHANUSH",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-[#250805]",
    cardGradClass: "from-[#450C07] via-[#6E140C] to-[#180503]",
    borderClass: "border-amber-400/70",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-red-950 text-amber-300 border-amber-400",
    headline: "Vijayadashami Special Offer!",
    tagline: "Celebrate the Victory of Good Over Evil in Grand Style!",
  },
  {
    id: "dussehra-victory-flame",
    name: "Triumphant Agni Flame",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Sacred victory flame with radiant solar rays, marigold garland framing & golden pedestal",
    tag: "VICTORY AGNI",
    isDark: true,
    accentHex: "#EA580C",
    accentBgClass: "bg-orange-600",
    containerBg: "bg-[#200A02]",
    cardGradClass: "from-[#3C1304] via-[#5C1D06] to-[#140601]",
    borderClass: "border-orange-400/60",
    titleColorClass: "text-orange-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-orange-500 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-orange-950 text-orange-300 border-orange-400",
    headline: "Dussehra Triumphant Mega Deal!",
    tagline: "Ignite Your Prosperity with This Season's Best!",
  },
  {
    id: "dussehra-royal-marigold",
    name: "Royal Marigold Toran",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Lavish dual-tier fresh Genda Phool toran with mango leaf swags and brass temple bells",
    tag: "GENDA TORAN",
    isDark: true,
    accentHex: "#FACC15",
    accentBgClass: "bg-yellow-400",
    containerBg: "bg-[#1E1102]",
    cardGradClass: "from-[#382004] via-[#573206] to-[#140B01]",
    borderClass: "border-yellow-400/60",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-400 text-black font-black",
    tagBadgeClass: "bg-amber-950 text-yellow-300 border-yellow-400",
    headline: "Shubh Dussehra Festive Offer!",
    tagline: "Welcome Prosperity & Joy into Your Home!",
  },
  {
    id: "dussehra-shubh-apta",
    name: "Golden Apta Sonpatta",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Sacred Apta tree golden leaf emblems symbolizing wealth sharing and auspicious beginnings",
    tag: "SHUBH APTA",
    isDark: true,
    accentHex: "#D97706",
    accentBgClass: "bg-amber-600",
    containerBg: "bg-[#181105]",
    cardGradClass: "from-[#2C1F0A] via-[#483311] to-[#100B03]",
    borderClass: "border-amber-400/60",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-amber-950 text-amber-300 border-amber-400",
    headline: "Auspicious Sonpatta Gold Offer!",
    tagline: "Gift the Pure Gold of Quality & Value!",
  },
  {
    id: "dussehra-ravan-dahan",
    name: "Ravan Dahan Spectacle",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Spectacular festival fireworks sparkles with burning effigy triumph sparkles and midnight glow",
    tag: "RAVAN DAHAN",
    isDark: true,
    accentHex: "#DC2626",
    accentBgClass: "bg-red-600",
    containerBg: "bg-[#1A0303]",
    cardGradClass: "from-[#300505] via-[#4C0808] to-[#120202]",
    borderClass: "border-red-400/60",
    titleColorClass: "text-red-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-red-500 to-amber-400 text-black font-black",
    tagBadgeClass: "bg-red-950 text-red-300 border-red-400",
    headline: "Grand Dussehra Festive Dhamaka!",
    tagline: "Unbeatable Festive Discounts for a Limited Time!",
  },
  {
    id: "dussehra-shastra-puja",
    name: "Regal Shastra Puja",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Royal Rajput weapons & armor heraldic crest with intricate royal gold scrollwork borders",
    tag: "SHASTRA PUJA",
    isDark: true,
    accentHex: "#B45309",
    accentBgClass: "bg-amber-700",
    containerBg: "bg-[#1C0E05]",
    cardGradClass: "from-[#321A0A] via-[#522B10] to-[#120903]",
    borderClass: "border-amber-400/70",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-amber-950 text-amber-300 border-amber-400",
    headline: "Royal Shastra Puja Edition!",
    tagline: "Honoring Heritage, Power & Flawless Craft!",
  },
  {
    id: "dussehra-ayudha-utsav",
    name: "Ayudha Puja Blessings",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Sacred tool & craft veneration with marigold garlands, chandan tilak & temple arch",
    tag: "AYUDHA PUJA",
    isDark: true,
    accentHex: "#CA8A04",
    accentBgClass: "bg-yellow-600",
    containerBg: "bg-[#1A1203]",
    cardGradClass: "from-[#312206] via-[#4D3609] to-[#120D02]",
    borderClass: "border-yellow-400/60",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-yellow-950 text-yellow-300 border-yellow-400",
    headline: "Ayudha Puja Auspicious Deals!",
    tagline: "Bless Your Everyday Tools with Premium Excellence!",
  },
  {
    id: "dussehra-vijaya-parv",
    name: "Vijaya Parv Grandeur",
    category: "Dussehra Special",
    festivalSection: "dussehra",
    description: "Grand palace gateway with royal saffron flags, floating marigold petals & golden podium",
    tag: "VIJAYA PARV",
    isDark: true,
    accentHex: "#EA580C",
    accentBgClass: "bg-orange-600",
    containerBg: "bg-[#240804]",
    cardGradClass: "from-[#400F07] via-[#63180B] to-[#160503]",
    borderClass: "border-orange-400/70",
    titleColorClass: "text-orange-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-orange-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-orange-950 text-orange-300 border-orange-400",
    headline: "Vijaya Parv Celebration Deals!",
    tagline: "Step Forward with the Mark of True Champions!",
  },

  // ================= 9 SHUBH DEEPAVALI CARDS (MATCHING REFERENCE IMAGE!) =================
  {
    id: "diwali-sacred-diya",
    name: "Sacred Diya & Marigold Arch",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Grand royal palace jharokha arch, cascading marigold garlands, 3D golden podium & glowing clay diyas (Reference Model)",
    tag: "DIWALI SPECIAL",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-[#200206]",
    cardGradClass: "from-[#4A030C] via-[#6B0613] to-[#180104]",
    borderClass: "border-amber-400/80",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-red-950 text-amber-300 border-amber-400",
    headline: "Diwali Special Offer!",
    tagline: "Light Up Your Festive Days with This Premium Pick!",
  },
  {
    id: "diwali-rangoli-mandala",
    name: "Imperial Rangoli Mandala",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Sacred radial 12-petaled Rangoli mandala overlay in pure 24K gold filigree with floating floor diyas",
    tag: "FESTIVE RANGOLI",
    isDark: true,
    accentHex: "#EAB308",
    accentBgClass: "bg-yellow-500",
    containerBg: "bg-[#180A22]",
    cardGradClass: "from-[#2A113C] via-[#431B60] to-[#12071A]",
    borderClass: "border-yellow-400/70",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-purple-950 text-yellow-300 border-yellow-400",
    headline: "Shubh Deepavali Special Offer!",
    tagline: "Colors, Lights & Joy in Every Festive Corner!",
  },
  {
    id: "diwali-akash-kandil",
    name: "Festival Akash Kandil",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Traditional hanging Indian paper lantern with flowing decorative festival tails & warm bokeh fairy lights",
    tag: "LANTERN FEST",
    isDark: true,
    accentHex: "#F43F5E",
    accentBgClass: "bg-rose-500",
    containerBg: "bg-[#1C0515]",
    cardGradClass: "from-[#340A28] via-[#521040] to-[#150410]",
    borderClass: "border-rose-400/60",
    titleColorClass: "text-rose-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-rose-500 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-rose-950 text-rose-300 border-rose-400",
    headline: "Akash Kandil Festive Glow!",
    tagline: "Illuminate Your World with Warm Festive Sparkles!",
  },
  {
    id: "diwali-royal-sparklers",
    name: "Celestial Fireworks Sparkler",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Radiating golden sparkler fireworks & celestial stardust particles on midnight velvet with golden pedestal",
    tag: "CELESTIAL SPARK",
    isDark: true,
    accentHex: "#FACC15",
    accentBgClass: "bg-yellow-400",
    containerBg: "bg-[#030712]",
    cardGradClass: "from-black via-zinc-950 to-slate-950",
    borderClass: "border-yellow-400/70",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-zinc-900 text-yellow-300 border-yellow-400/60",
    headline: "Diwali Sparkler Festive Mega Sale!",
    tagline: "Sparkle & Shine with Premium Festive Specials!",
  },
  {
    id: "diwali-dhamaka-gold",
    name: "Grand Diwali Dhamaka",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Grand festival sale starburst seal flanked by twin burning brass oil lamps, marigold swags & 3D royal stage",
    tag: "DIWALI DHAMAKA",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-[#1E0202]",
    cardGradClass: "from-[#380404] via-[#5C0707] to-[#140101]",
    borderClass: "border-amber-400",
    titleColorClass: "text-amber-200 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-red-600 text-white font-black border-yellow-400",
    headline: "Maha Diwali Dhamaka Offer!",
    tagline: "Biggest Festive Discounts of the Year • Shop Now!",
  },
  {
    id: "diwali-dhanteras-shubh",
    name: "Shubh Dhanteras Gold",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Auspicious Dhanteras golden Kalash overflowing with Laxmi gold coins, lotus petals & burning ghee diyas",
    tag: "SHUBH DHANTERAS",
    isDark: true,
    accentHex: "#EAB308",
    accentBgClass: "bg-yellow-500",
    containerBg: "bg-[#1F1202]",
    cardGradClass: "from-[#3A2204] via-[#5C3607] to-[#150C01]",
    borderClass: "border-yellow-400/80",
    titleColorClass: "text-yellow-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-yellow-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-amber-950 text-yellow-300 border-yellow-400",
    headline: "Shubh Dhanteras Gold Offer!",
    tagline: "Bring Home Prosperity, Fortune & Timeless Value!",
  },
  {
    id: "diwali-laxmi-puja",
    name: "Maa Laxmi Divine Lotus",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Divine pink lotus floral gateway with golden blessings aura, silver coin borders & glowing aarti lamps",
    tag: "LAXMI PUJA",
    isDark: true,
    accentHex: "#EC4899",
    accentBgClass: "bg-pink-500",
    containerBg: "bg-[#240614]",
    cardGradClass: "from-[#420B25] via-[#66113A] to-[#17040E]",
    borderClass: "border-pink-400/70",
    titleColorClass: "text-pink-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-pink-400 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-pink-950 text-pink-300 border-pink-400",
    headline: "Laxmi Puja Divine Prosperity Sale!",
    tagline: "Embrace Abundance & Joy with Sacred Quality!",
  },
  {
    id: "diwali-bhai-dooj",
    name: "Bhai Dooj Festive Love",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Sacred Roli-Tikka emblem with festive mithai garland, floral arch & warm celebratory lanterns",
    tag: "BHAI DOOJ",
    isDark: true,
    accentHex: "#DC2626",
    accentBgClass: "bg-red-600",
    containerBg: "bg-[#220408]",
    cardGradClass: "from-[#3E070F] via-[#610B18] to-[#180306]",
    borderClass: "border-amber-400/60",
    titleColorClass: "text-red-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-red-500 to-amber-300 text-black font-black",
    tagBadgeClass: "bg-red-950 text-red-300 border-amber-400",
    headline: "Bhai Dooj Special Gift Box!",
    tagline: "The Perfect Gift to Celebrate Everlasting Bonds!",
  },
  {
    id: "diwali-patakha-celebration",
    name: "Festive Joy Fireworks",
    category: "Diwali Special",
    festivalSection: "diwali",
    description: "Vibrant phuljhadi sparkler bursts, festive chakra spinners, golden floor lights & royal celebration stage",
    tag: "FESTIVE LIGHTS",
    isDark: true,
    accentHex: "#F59E0B",
    accentBgClass: "bg-amber-500",
    containerBg: "bg-[#180312]",
    cardGradClass: "from-[#2E0623] via-[#4A0A38] to-[#12020E]",
    borderClass: "border-amber-400/70",
    titleColorClass: "text-amber-100 font-serif font-black",
    priceColorClass: "text-yellow-300",
    ctaClass: "bg-gradient-to-r from-amber-400 to-yellow-300 text-black font-black",
    tagBadgeClass: "bg-purple-950 text-amber-300 border-amber-400",
    headline: "Diwali Lights Celebration Special!",
    tagline: "Spread Light & Joy This Festive Season!",
  },
];

export const CARD_TEMPLATES_MAP: Record<TemplateId, CardTemplateInfo> = Object.fromEntries(
  CARD_TEMPLATES_INFO.map((t) => [t.id, t])
) as Record<TemplateId, CardTemplateInfo>;
